# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  IISWebsiteName: 'QASite'
resources: 
 pipelines: 
      - pipeline: 'buildpipeline' #to fill
        project: 'YMLWebAPI'
        source: ''
        branch: 'main'

stages:
  - stage: 'Deploywebsite'
    displayName: 'Display web site'
    pool: 'windows-latest'
    
    jobs:
    - deployment: Deploywebsite
      displayName: 'Display web site'
      environment: 'Windows10.MyServerVM'
      strategy:
       runOnce:
           deploy:
            steps:
                 - checkout: none
                 - download: 'buildpipeline'
                   name: 'DownloadBuildArtifacts'
                   displayName: 'Download Build Artifact
                   artifact; ''# to fill
                   - task: IISWebAppManagementOnMachineGroup@0
                     inputs:
                       IISDeploymentType: 'IISWebsite'
                       ActionIISWebsite: 'StopWebsite'
                       StartStopWebsiteName: '$(( variables.IISWebsiteName ))'
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
